RimMenswearShop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RimMenswearShop.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RimMenswearShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RimMenswearShop.Models;
using RimMenswearShop.Models.Cart;
using RimMenswearShop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RimMenswearShop.Controllers
{
    [AllowAnonymous]
    public class CartController : Controller
    {        
        private const string CartSession = "CartSession";
        private readonly AppDbContext context;
        private readonly IProductRepository productRepository;

        public CartController(AppDbContext context, IProductRepository productRepository)
        {
            this.context = context;
            this.productRepository = productRepository;
        }
        public IActionResult Index(string id)
        {
            ViewBag.Products = productRepository.Get().ToList();
            ViewBag.ProductId = id;
            ViewBag.Product = (from p in context.Products where p.IsDeleted == false && p.ProductId == id select p)
                .ToList().FirstOrDefault();
            var cart = HttpContext.Session.GetObjectFromJson<List<Item>>(CartSession);
            HttpContext.Session.SetObjectAsJson(CartSession, cart);

            return View(cart);
        }

        [Route("/Cart/AddItem/{id}")]
        public IActionResult AddItem(string id)
        {
            Item item = new Item() { ProductId = id, Amount = 1 };
            var cart = HttpContext.Session.GetObjectFromJson<List<Item>>(CartSession);

            if (cart.Count != 0)
            {
                if (cart.Exists(el => el.ProductId == item.ProductId))
                {
                    cart.FirstOrDefault(el => el.ProductId == item.ProductId).Amount += 1;
                    HttpContext.Session.SetObjectAsJson(CartSession, cart);
                    return Json(-1);
                }
                else
                {
                    cart.Add(item);
                    HttpContext.Session.SetObjectAsJson(CartSession, cart);
                    return Json(cart.Count);
                }
            }
            cart.Add(item);
            HttpContext.Session.SetObjectAsJson(CartSession, cart);

            return Json(cart.Count);
        }
    }
}

RimMenswearShop/Views/Shared/AdminLayout.cshtml
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager
@inject AppDbContext context
@{
    var currentUser = userManager.FindByNameAsync(User.Identity.Name).Result;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Trang Admin</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    @RenderSection("lightboxcss", false)
    @RenderSection("datatablecss", false)
    @RenderSection("RemoveImageCss", false)
    <link href="~/css/DashboardStyles.css" rel="stylesheet" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-info">
        <a class="navbar-brand" asp-controller="Admin" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Bảng điều khiển</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search-->
        <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        </div>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-controller="Home" asp-action="Index" target="_blank">Trang chủ</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Thoát</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Quản lý sản phẩm</div>
                        <a class="nav-link" asp-controller="Product" asp-action="Index">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-file"></i>
                            </div>
                            Sản phẩm
                        </a>
                        <a class="nav-link" asp-controller="Categories" asp-action="Index">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-list"></i>
                            </div>
                            Danh mục
                        </a>
                        <a class="nav-link" asp-controller="Brands" asp-action="Index">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-tags"></i>
                            </div>
                            Thương hiệu
                        </a>
                        <div class="sb-sidenav-menu-heading">Quản lý đơn hàng</div>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="PendingOrders">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-hourglass-half"></i>
                            </div>
                            Chưa xử lý
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="ProcessingOrders">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-angle-double-right"></i>
                            </div>
                            Đang vận chuyển
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="CompletedOrders">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-check-circle"></i>
                            </div>

                            Đã giao hàng
                        </a>
                        <a class="nav-link" asp-controller="OrdersManager" asp-action="CanceledOrders">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-times-circle"></i>
                            </div>
                            Đã huỷ
                        </a>
                        <div class="sb-sidenav-menu-heading">Quản lý thành viên</div>
                        <a class="nav-link" asp-controller="Role" asp-action="Index">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-user-tag"></i>
                            </div>
                            Vai trò
                        </a>
                        <a class="nav-link" asp-controller="User" asp-action="Index">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-users"></i>
                            </div>
                            Thành viên
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <h2 class="text-center my-4">@ViewBag.Title</h2>
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; @DateTime.Now.Year </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/font-awesome/js/all.js"></script>
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
    </environment>
    <script src="~/js/DashboardScripts.js"></script>
    @RenderSection("Scripts", false)
    @RenderSection("ValidateScript", false)
    @RenderSection("lightboxjs", false)
    @RenderSection("datatablejs", false)
    @RenderSection("tinyMCE", false)
</body>
</html>

RimMenswearShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity; 
@inject SignInManager<ApplicationUser> signInManager
@inject AppDbContext context
@{ 
    var categories = (from c in context.Categories where c.IsDeleted == false select c).ToList();
    var brands = (from b in context.Brands where b.IsDeleted == false select b).ToList();

}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>RIM Accessories - Cửa hàng phụ kiện Nam chính hãng</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">

    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/assets/css/magnific-popup.css">

    <link rel="stylesheet" href="~/assets/css/aos.css">

    <link rel="stylesheet" href="~/assets/css/ionicons.min.css">

    <link rel="stylesheet" href="~/assets/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/assets/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/assets/css/flaticon.css">
    <link rel="stylesheet" href="~/assets/css/icomoon.css">
    <link href="~/css/lol.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <style>
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
    </style>
    @RenderSection("LoginCSS", false)

</head>
<body class="goto-here">
    <div class="py-1 bg-black">
        <div class="container">
            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
                <div class="col-lg-12 d-block">
                    <div class="row d-flex">
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                            <span class="text">+ 098 333 6103</span>
                        </div>
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                            <span class="text">rimaccessories@gmail.com</span>
                        </div>
                        <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                            <span class="text">Free Ship với hóa đơn trên 500k</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">RIM ACCESSORIES</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a asp-controller="Home" asp-action="Index" class="nav-link">Trang Chủ</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sản phẩm</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            @{
                                foreach (var category in categories)
                                {
                                    <a class="dropdown-item" asp-controller="Home" asp-action="Category" asp-route-id="@category.CategoryId">@category.Name</a>
                                }
                            }
                        </div>
                    </li>
                    <li class="nav-item"><a asp-controller="Home" asp-action="About" class="nav-link">Giới thiệu</a></li>
                    <li class="nav-item"><a asp-controller="Home" asp-action="Contact" class="nav-link">Liên hệ</a></li>
                    <li class="nav-item cta cta-colored"><a asp-controller="Cart" asp-action="Index" class="nav-link"><span class="icon-shopping_cart" id="CartNum">0</span></a></li>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Index">Trang Admin</a>
                                }
                                <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword">Đổi mật khẩu</a>
                                <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Đăng xuất</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item"><a asp-controller="Account" asp-action="Login" class="nav-link">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="ftco-footer bg-light ftco-section">
        <div class="container">
            <div class="row">
                <div class="mouse">
                    <a href="#" class="mouse-icon">
                        <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                    </a>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Rim Accesories</h2>
                        <p>Cửa hàng phụ kiện nam chính hãng 1970s.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Menu</h2>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Home" asp-action="Index" class="py-2 d-block">Trang chủ</a></li>
                            <li><a asp-controller="Home" asp-action="About">Giới thiệu</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Điều khoản dịch vụ</h2>
                        <div class="d-flex">
                            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                                <li><a href="#" class="py-2 d-block">Chính sách quy định</a></li>
                                <li><a href="#" class="py-2 d-block">Hướng dẫn mua hàng</a></li>
                                <li><a href="#" class="py-2 d-block">Chính sách đổi trả</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Thông tin liên hệ</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">27 Ngự Bình, Phường An Cựu, TP Huế, Việt Nam</span></li>
                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+ 098 333 6103</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">rimaccesories@gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> <i class="icon-heart color-danger" aria-hidden="true"></i> by Long T</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/lib/datatable/js/datatable.jquery.min.js"></script>
    <script src="~/lib/datatablenet/jquery.dataTables.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/jquery.easing.1.3.js"></script>
    <script src="~/assets/js/jquery.waypoints.min.js"></script>
    <script src="~/assets/js/jquery.stellar.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/js/aos.js"></script>
    <script src="~/assets/js/jquery.animateNumber.min.js"></script>
    <script src="~/assets/js/bootstrap-datepicker.js"></script>
    <script src="~/assets/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/assets/js/google-map.js"></script>
    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/bootbox/bootbox.min.js"></script>
    <script src="~/js/CustomerCart.js" asp-append-version="true"></script>
    @RenderSection("Scripts", false)
    @RenderSection("ValidateScript", false)
    @RenderSection("lightboxjs", false)
    @RenderSection("datatablejs", false)
    @RenderSection("tinyMCE", false)
</body>
</html>